name: Lazyflow
options:
  bundleIdPrefix: com.lazyflow
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.7.0
    DEVELOPMENT_TEAM: WMK84PPNJV

targets:
  Lazyflow:
    type: application
    platform: iOS
    sources:
      - path: Lazyflow/Sources
      - path: Lazyflow/Resources
      - path: LazyflowWidget/LiveActivity/TaskActivityAttributes.swift
    info:
      path: Lazyflow/Resources/Info.plist
      properties:
        NSSupportsLiveActivities: YES
        NSCalendarsFullAccessUsageDescription: "Lazyflow needs calendar access to schedule tasks as time blocks and show your events alongside tasks."
        UIBackgroundModes:
          - remote-notification
        INAlternativeAppNames:
          - INAlternativeAppName: Lazy Flow
          - INAlternativeAppName: Todo
          - INAlternativeAppName: Planner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lazyflow.app
        INFOPLIST_KEY_CFBundleDisplayName: Lazyflow
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Lazyflow/Lazyflow.entitlements
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_NSSiriUsageDescription: "Lazyflow uses Siri to create tasks and check your agenda"
    dependencies:
      - target: LazyflowWidget
        embed: true
      - target: LazyflowWatch
        embed: true
    scheme:
      testTargets:
        - LazyflowTests
        - LazyflowUITests

  LazyflowWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: LazyflowWidget
        excludes:
          - "**/*.xcassets"
      - path: LazyflowWidget/Assets.xcassets
    info:
      path: LazyflowWidget/Info.plist
      properties:
        CFBundleDisplayName: Lazyflow Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lazyflow.app.widget
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: LazyflowWidget/LazyflowWidget.entitlements
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  LazyflowTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LazyflowTests
    dependencies:
      - target: Lazyflow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lazyflow.app.tests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Lazyflow.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Lazyflow"

  LazyflowUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LazyflowUITests
    dependencies:
      - target: Lazyflow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lazyflow.app.uitests
        TEST_TARGET_NAME: Lazyflow

  LazyflowWatch:
    type: application
    platform: watchOS
    sources:
      - path: LazyflowWatch/Sources
      - path: LazyflowWatch/Resources
    info:
      path: LazyflowWatch/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lazyflow.app.watch
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.lazyflow.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: LazyflowWatch/LazyflowWatch.entitlements
        ENABLE_PREVIEWS: YES
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
