name: Taskweave
options:
  bundleIdPrefix: com.taskweave
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.6.0

targets:
  Taskweave:
    type: application
    platform: iOS
    sources:
      - path: Taskweave/Sources
      - path: Taskweave/Resources
    info:
      path: Taskweave/Resources/Info.plist
      properties:
        INAlternativeAppNames:
          - INAlternativeAppName: Task Weave
          - INAlternativeAppName: Task weave
          - INAlternativeAppName: Tasks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app
        INFOPLIST_KEY_CFBundleDisplayName: Taskweave
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Taskweave/Taskweave.entitlements
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_NSSiriUsageDescription: "Taskweave uses Siri to create tasks and check your agenda"
    dependencies:
      - target: TaskweaveWidget
        embed: true
    scheme:
      testTargets:
        - TaskweaveTests
        - TaskweaveUITests

  TaskweaveWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: TaskweaveWidget
        excludes:
          - "**/*.xcassets"
      - path: TaskweaveWidget/Assets.xcassets
    info:
      path: TaskweaveWidget/Info.plist
      properties:
        CFBundleDisplayName: Taskweave Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app.widget
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: TaskweaveWidget/TaskweaveWidget.entitlements
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  TaskweaveTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TaskweaveTests
    dependencies:
      - target: Taskweave
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app.tests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Taskweave.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Taskweave"

  TaskweaveUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TaskweaveUITests
    dependencies:
      - target: Taskweave
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app.uitests
        TEST_TARGET_NAME: Taskweave
