name: Taskweave
options:
  bundleIdPrefix: com.taskweave
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.2.0

targets:
  Taskweave:
    type: application
    platform: iOS
    sources:
      - path: Taskweave/Sources
      - path: Taskweave/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app
        INFOPLIST_KEY_CFBundleDisplayName: Taskweave
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
    scheme:
      testTargets:
        - TaskweaveTests
        - TaskweaveUITests

  TaskweaveTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TaskweaveTests
    dependencies:
      - target: Taskweave
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app.tests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Taskweave.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Taskweave"

  TaskweaveUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TaskweaveUITests
    dependencies:
      - target: Taskweave
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskweave.app.uitests
        TEST_TARGET_NAME: Taskweave
